import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Footer from "./_components/Footer/Footer";
import Navbar from "./_components/Navbar/Navbar";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Centrum Druku Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
